"""llms.txt generator — creates AI-discoverable index from ingested API specs."""

from agentbridge.models.endpoint import Endpoint
from agentbridge.models.project import Project


def generate_llms_txt(project: Project, endpoints: list[Endpoint], base_url: str = "") -> str:
    """Generate an llms.txt document for a project's API endpoints."""

    lines: list[str] = []

    # ── Header ──
    lines.append(f"# {project.name} — generated by agentbridge")
    if project.description:
        lines.append(f"# {project.description}")
    if base_url:
        lines.append(f"# Base URL: {base_url}")
    lines.append("")

    # ── Quick Start ──
    lines.append("## Quick Start")
    lines.append("Connect any MCP-compatible agent:")
    if base_url:
        lines.append(f"- MCP Endpoint: {base_url}/mcp/")
    lines.append(f"- Project ID: {project.id}")
    lines.append(f"- Endpoints: {len(endpoints)}")
    lines.append("")

    # ── MCP Server Config ──
    lines.append("## MCP Configuration")
    lines.append("Add this to your MCP client config:")
    lines.append("```json")
    mcp_config = {
        "mcpServers": {
            project.name: {"url": f"{base_url}/mcp/"} if base_url else {"command": "agentbridge", "args": ["serve"]}
        }
    }
    import json as _json
    lines.append(_json.dumps(mcp_config, indent=2))
    lines.append("```")
    lines.append("")

    # ── Tools (Endpoints) ──
    lines.append("## MCP Tools")
    lines.append(f"{len(endpoints)} tools generated from {project.artifact_count} artifact(s):")
    lines.append("")

    # Group by tag
    tagged: dict[str, list[Endpoint]] = {}
    untagged: list[Endpoint] = []
    for ep in endpoints:
        if ep.tags:
            for tag in ep.tags:
                tagged.setdefault(tag, []).append(ep)
        else:
            untagged.append(ep)

    for tag, eps in sorted(tagged.items()):
        lines.append(f"### {tag}")
        for ep in eps:
            lines.append(_format_endpoint(ep))
        lines.append("")

    if untagged:
        lines.append("### General")
        for ep in untagged:
            lines.append(_format_endpoint(ep))
        lines.append("")

    # ── Resources ──
    lines.append("## MCP Resources")
    for ep in endpoints:
        lines.append(f"- `{ep.path}` — {ep.summary or ep.method.value} {ep.path}")
    lines.append("")

    # ── Auth Info ──
    auth_endpoints = [ep for ep in endpoints if ep.auth_required]
    if auth_endpoints:
        lines.append("## Authentication")
        lines.append(f"{len(auth_endpoints)} endpoints require authentication")
        if project.auth_scheme and project.auth_header:
            lines.append(f"- Scheme: {project.auth_scheme}")
            lines.append(f"- Header: {project.auth_header}")
        lines.append("")

    # ── For AI Agents ──
    lines.append("## For AI Agents")
    lines.append("This file follows the llms.txt standard (https://llmstxt.org).")
    if base_url:
        lines.append(f"Health check: {base_url}/health")
        lines.append(f"OpenAPI spec: {base_url}/openapi.json")
    lines.append(f"Artifacts ingested: {project.artifact_count}")
    lines.append(f"Generated: {project.created_at.isoformat() if project.created_at else 'unknown'}")
    lines.append(f"agentbridge version: 0.2.0")

    return "\n".join(lines)


def _format_endpoint(ep: Endpoint) -> str:
    name = ep.summary or f"{ep.method.value}_{ep.path.replace('/', '_').strip('_')}"
    name = name.lower().replace(" ", "_").replace("-", "_")

    param_list = ", ".join(f"{p.name}: {p.type}" + ("?" if not p.required else "") for p in ep.parameters)

    lines = [f"- **{name}** `{ep.method.value} {ep.path}`"]
    if ep.description:
        lines.append(f"  {ep.description}")
    if param_list:
        lines.append(f"  Params: {param_list}")
    if ep.auth_required:
        auth = f" ({ep.auth_type})" if ep.auth_type else ""
        lines.append(f"  🔒 Auth required{auth}")

    return "\n".join(lines)
